Update README.md
contentlayerdev/contentlayer pull request #97
Opened 2022-01-09 13:51 UTC by adeecc

Have been using contentlayer to serve my Blog. Adding it to the list via PR

2022-01-14 12:28 UTC, schickling requested changes

2022-01-14 12:28 UTC, schickling commented on packages/contentlayer/README.md
> -
Please remove this line break change

2022-01-14 12:28 UTC, schickling commented on packages/contentlayer/README.md
> +-
Please remove this line break change

2022-02-03 16:23 UTC, closed without merging

2022-02-03 16:24 UTC, adeecc commented
Created a new pr with changes you requested.